title: "<p align='center'>Muna Faizatun Nabilah</p>"

logo: "/images/logo.png?raw=true"

description: |
  <div align="center">
    <a href="https://www.linkedin.com/in/munafaizatunabilah/">LinkedIn</a> |
    <a href="https://github.com/munafaizatun">GitHub</a>
  </div>

  <div align="justify">
    Data tells a story â€” and I love reading it. I'm Muna Faizatun Nabilah, a Statistics graduate on a mission to turn complex data into clear, actionable insights. By combining analytical thinking with modeling and visualization, I help uncover hidden patterns, solve real-world problems, and drive decisions that truly make an impact.
  </div>

theme: jekyll-theme-minimal
google_analytics: G-0FMPR2V8ZS  # GA4 Measurement ID
