title: "<p align='center'>Muna Faizatun Nabilah</p>"

logo: "/images/logo.png?raw=true"

description: |
  <p align="center">
    <a href="https://www.linkedin.com/in/munafaizatunabilah/">LinkedIn</a> |
    <a href="https://github.com/munafaizatun">GitHub</a>
  </p>

  <p align="justify">
      Data tells a story â€” and I love reading it. I'm Muna Faizatun Nabilah, a Statistics graduate passionate about turning data into actionable insights. I combine analytical thinking with modeling and visualization skills to look beyond numbers and drive impactful, data-driven decisions.
  </p>

theme: jekyll-theme-minimal

google_analytics: G-0FMPR2V8ZS  # GA4 Measurement ID
