title: "<p align='center'>Muna Faizatun Nabilah</p>"

logo: "/images/logo.png?raw=true"

description: |
  <p align="center">
    <a href="https://www.linkedin.com/in/munafaizatunabilah/">LinkedIn</a> |
    <a href="https://github.com/munafaizatun">GitHub</a>
  </p>

  <p align="justify">
    I turn data into insights. I'm Muna, a Statistics graduate who transforms complex datasets into actionable strategies. Combining analytical thinking with modeling and visualization, I help uncover hidden patterns, solve real-world problems, and drive impactful decisions.
  </p>

theme: jekyll-theme-minimal
google_analytics: G-0FMPR2V8ZS  # GA4 Measurement ID
