title: "<p align='center'>Muna Faizatun Nabilah</p>"

logo: "/images/logo.png?raw=true"

description: |
  <p align="center">
    <a href="https://www.linkedin.com/in/munafaizatunabilah/">LinkedIn</a> |
    <a href="https://github.com/munafaizatun">GitHub</a>
  </p>

  <p align="justify">
  I turn messy datasets into insights and patterns that tell a story, combining technical skills with an analytical mindset and a curiosity to keep learning.
  </p>

theme: jekyll-theme-minimal
google_analytics: G-0FMPR2V8ZS  # GA4 Measurement ID
